export const TEMPLATES = [
  {
    name: "「慕课乐高」标准项目模板",
    npmName: "@imooc-cli/imooc-lego-standard-template",
    version: "1.0.0",
    type: "normal",
    installCommand: "npm install",
    startCommand: "npm run serve",
    ignore: ["**/public/**"],
    tag: ["project"],
    buildPath: "dist",
  },
  {
    name: "Vue2 标准项目模板",
    npmName: "@imooc-cli/vue2-standard-template",
    version: "1.0.0",
    type: "normal",
    startCommand: "npm run serve",
    ignore: ["**/public/**"],
    tag: ["project"],
    buildPath: "dist",
  },
  {
    name: "React 标准项目模板",
    npmName: "@imooc-cli/react-standard-template",
    version: "1.0.0",
    type: "normal",
    startCommand: "npm start",
    tag: ["project"],
    buildPath: "build",
  },
  {
    name: "Vue3 标准项目模板",
    npmName: "@imooc-cli/vue3-standard-template",
    version: "1.0.0",
    type: "normal",
    startCommand: "npm run serve",
    ignore: ["**/public/**"],
    tag: ["project"],
    buildPath: "dist",
  },
  {
    name: "慕课网前端标准项目模板（Vue3.0）",
    npmName: "@imooc-cli/imooc-standard-template",
    version: "1.0.0",
    type: "custom",
    tag: ["project"],
    buildPath: "dist",
  },
  {
    name: "vue-admin-template项目模板",
    value: "template-vue-element-admin",
    npmName: "@zcxiaobao-cli/template-vue-element-admin",
    version: "1.0.0",
    forceInstallNew: true,
    tag: ["project"],
    startCommand: "npm run dev",
    ignore: ["**/public/**", "**/assets/**"],
  },
  {
    name: "Vue3 标准组件模板",
    npmName: "@imooc-cli/vue3-component",
    version: "1.0.0",
    type: "normal",
    tag: ["component"],
    startCommand: "npm run dev",
    buildPath: "dist",
    examplePath: "examples",
  },
  {
    name: "慕课乐高组件库模板",
    npmName: "imooc-cli-dev-lego-components",
    version: "1.0.0",
    type: "normal",
    tag: ["component"],
    startCommand: "npm run serve",
    buildPath: "dist",
    examplePath: "examples",
    ignore: ["**/public/**", "**.png"],
  },
];

export const ADD_TYPE = {
  COMPONENT: "component",
  PROJECT: "project",
};

export const ADD_TYPE_LIST = [
  { name: "项目", value: ADD_TYPE.PROJECT },
  { name: "组件", value: ADD_TYPE.COMPONENT },
];
